### PR TITLE
Preliminary bug fixes

### LINKED ISSUE #121: [PE-D] UG Quickstart guide .jar naming incorrect
It should be CliverShelf.jar instead of Duke.jar and the run command should have been `java -jar CliverShelf.jar` instead

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: kyun99/ped#1

### LINKED ISSUE #122: [PE-D] Typo in error message for list command
"Does not exist" appears twice in the error message.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: avellinwong01/ped#1

### LINKED ISSUE #123: [PE-D] Screenshot of application start up is not available
A screenshot should be present here 

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: kyun99/ped#2

### LINKED ISSUE #124: [PE-D] Incomplete usage description
I'm not sure if a picture or text should show up here

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: kyun99/ped#3

### LINKED ISSUE #125: [PE-D] Error message and documentation for add command
Did not specify in error message or in UG that it is necessary to create a shelf before adding items

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: avellinwong01/ped#2

### LINKED ISSUE #126: [PE-D] Suggestions to improve error message to user for list command
Would be good to inform the user in the error message that a shelf (rather than item container) has not been created and how to create a shelf. 
The part in the Warning message about GetCommand failing to execute may not be necessary to be shown to the user (as it looks more like an error message shown by IDE) 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: avellinwong01/ped#3

### LINKED ISSUE #127: [PE-D] Documentation for List Command in UG
UG did not document the necessary condition for a shelf to exist for list shlv/SHELF_NAME command.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: avellinwong01/ped#4

### LINKED ISSUE #132: [PE-D] Incorrect error message for list command
The suggested solution shown from the error message does not work.

Prompted `List` input to show list of shelves when incorrect input is given but when `List` is given, an error message appeared

Expected: a list of shelves

Actual: invalid command error message

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: kyun99/ped#4

### LINKED ISSUE #134: [PE-D] Mistake in error message for delete command
Keyed in index 6 but error message says index 5

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: avellinwong01/ped#8

### LINKED ISSUE #135: [PE-D] Unclear invalid command report
There is no information mentioning that the name of bookshelf cannot contain white space or other symbols like '&'. The error report just indicated that the input is in invalid format but did not give more detailed restriction for 'SHELF_NAME', which may make users confused.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Mist0919/ped#2

### LINKED ISSUE #136: [PE-D] Remarks of item does not appear after get command
After adding an item with a remark, I tried viewing the information. However, the remarks seem to be empty and doesn't show up.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: mohamedirfansh/ped#3

### LINKED ISSUE #140: [PE-D] Error message for delete function does not show the correct index number
tried to delete a item with index not in `warehouse` but got an incorrect error message

Expected: Item with index 3 does not exist  

Actual: Item with index 2 does not exist

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: kyun99/ped#5

### LINKED ISSUE #150: [PE-D] Inaccuracies in Error message for report command
As you already have a different list command, shouldn't the warning message be report command instead? 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: avellinwong01/ped#16

### PR DESCRIPTION
**Pull request by zh1huang**
Closes #121 
Closes #122 
Closes #123 
Closes #124 
Closes #125 
Closes #126 
Closes #127 
Closes #132 
Closes #134
Closes #135
Closes #136 
Closes #150

### CODE REVIEW

**Review by yuejunfeng0909 — APPROVED** [review]
looks good to merge

File: src/main/java/seedu/duke/ui/MessageBubble.java [hunk 1]
```diff
@@ -7,8 +7,8 @@
     static final String EDGE_VERTICAL_SYMBOL = ":";
     static final String EDGE_TAIL = "...";
     static int MAX_LINES = 1000;
-    static int TERMINAL_WIDTH = 80;
-    static int MAX_BUBBLE_WIDTH = 70;
+    static int TERMINAL_WIDTH = 105;
+    static int MAX_BUBBLE_WIDTH = 105;
```
Comment (yuejunfeng0909) [inline src/main/java/seedu/duke/ui/MessageBubble.java:11]: Try to set the MAX_BUBBLE_WIDTH smaller than the terminal width so that the lefthand side of the bubble will not touch the left side of the terminal.

**Review by yuejunfeng0909 — CHANGES_REQUESTED** [review]
Overall good, only some small UI issue
