### PR TITLE
Reformat report details & bug fixes

### LINKED ISSUE #143: [PE-D] Suggestion for soldItems shelf
Personally don't think items that have been sold should be allowed to have their cost and price edited (as after all they are already sold) 

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: avellinwong01/ped#13

### LINKED ISSUE #172: Report item details reformat

### LINKED ISSUE #176: Edit Parser sell user input command format
Previous: 
sell shlv/SHELF_NAME i/INDEX

New:
sell id/ITEM_ID

### LINKED ISSUE #181: Restrict adding items if updated quantity exceeds 999
image

### LINKED ISSUE #193: Limit shelf size
So that program will not crash should user include adding overly high quantities of items

### PR DESCRIPTION
**Pull request by haoyusimon**
Closes #193 
Closes #181 
Closes #176 
Closes #172 
Closes #143

### CODE REVIEW

**Review by zh1huang — APPROVED** [review]
Looks good to merge

**Review by t-l-xin — APPROVED** [review]
Looks good to merge

File: src/main/java/seedu/duke/model/ShelfList.java [hunk 1]
```diff
@@ -101,7 +101,10 @@ public void deleteShelf(String name) throws ShelfNotExistException {
      *
      * @throws ShelfNotExistException If no Shelf in the ShelfList has the specified name
      */
-    public Shelf getShelf(String name) throws ShelfNotExistException {
+    public Shelf getShelf(String name, boolean isSoldItemHidden) throws ShelfNotExistException {
```
Comment (yuejunfeng0909) [inline src/main/java/seedu/duke/model/ShelfList.java:104]: Overload this method. Do not overwrite the original method.

**Review by yuejunfeng0909 — CHANGES_REQUESTED** [review]
